### ISSUE TITLE
request the dataset

### ISSUE THREAD

**Issue by sim1n999** [jadeCurl/FFRR#1]
Thank you very much for your excellent work. I have a strong interest in your research and I find your approach very inspiring and appreciate that you have open sourced your code. However, I am having problems downloading the dataset `RAWFC`. Dropbox rejected my download request because of the number of files.

Can I please ask you to package it in zip or 7z? I guarantee that all data is used strictly for academic purposes and meets any conditions you specify. I have starred your project and if it goes well I will also cite your research in my paper. I would like you to upload the data somewhere if possible, or send it to me via e-mail at `siming8741@gmail.com`. 

Thanks again for your contribution to the field!

**Comment by jadeCurl** [comment]
Hi, Thanks for your interest in our work! But the datasets are not collected and released by us, maybe you can contact the original author :)
